# Generated by Django 4.1.7 on 2023-03-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_alter_review_name")]

    operations = [migrations.RemoveField(model_name="signup", name="username")]
