# Generated by Django 4.1.7 on 2023-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_remove_signup_username")]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="username",
            field=models.CharField(blank=True, max_length=30, null=True),
        )
    ]
