# Generated by Django 4.1.7 on 2023-04-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_signup_username")]

    operations = [migrations.RemoveField(model_name="signup", name="username")]
